{% set name = "adjustText" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Phlya/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 19ed397f577b61681d54c34808ee8df7aaa525d12313027d94ca54b215d323a3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - matplotlib-base
    - numpy
    - python

test:
  imports:
    - adjustText

about:
  home: https://github.com/Phlya/adjustText
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic label placement for matplotlib
  doc_url: http://adjusttext.readthedocs.io/
  dev_url: https://github.com/Phlya/adjustText

extra:
  recipe-maintainers:
    - phue
