{% set name = "adjustText" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Phlya/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3aad0ae808f1cdd1b4f8d8ccbf933b414cb080d6bf000c4bcb2d927b1ae98c6f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - matplotlib-base
    - numpy
    - python

test:
  imports:
    - adjustText

about:
  home: https://github.com/Phlya/adjustText
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Automatic label placement for matplotlib'
  doc_url: http://adjusttext.readthedocs.io/
  dev_url: https://github.com/Phlya/adjustText

extra:
  recipe-maintainers:
    - phue
