{% set name = "adjustText" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Phlya/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f7e4bf5b68fe10fa275a09e1582fbe76326ad7f42d6d86bd15a1a126d9708c33

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - matplotlib-base
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - adjustText

about:
  home: https://github.com/Phlya/adjustText
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Automatic label placement for matplotlib'
  doc_url: http://adjusttext.readthedocs.io/
  dev_url: https://github.com/Phlya/adjustText

extra:
  recipe-maintainers:
    - phue
