{% set name = "adjustText" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Phlya/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 90dfa57a0b7b4382d5a273f6e672f3fe12ca32f38f7c4d286e78ffe0c87b531c

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - adjustText

about:
  home: https://github.com/Phlya/adjustText
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Automatic label placement for matplotlib'
  doc_url: http://adjusttext.readthedocs.io/
  dev_url: https://github.com/Phlya/adjustText

extra:
  recipe-maintainers:
    - phue
