{% set name = "adjustText" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Phlya/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 95528b382ef5ac468d72f6d7bbacc4ea972f44ed0aad701108ef06ac0dd48a04

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - matplotlib-base
    - numpy
    - python

test:
  imports:
    - adjustText

about:
  home: https://github.com/Phlya/adjustText
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Automatic label placement for matplotlib'
  doc_url: http://adjusttext.readthedocs.io/
  dev_url: https://github.com/Phlya/adjustText

extra:
  recipe-maintainers:
    - phue
